ci: fix publish-dockerhub (DAEMONS)
Commit 82b9ba16, part of #816, broke upload of all DAEMONS but
base. The reason why it wasn't detected is because composite action
leaves DAEMONS set, so step 3 passes and step 4 just uploads
the single daemon base.

Fix it by defining it globally, and add a check for the list of
DAEMONS as part of step2, so that this is not happening again.

diff --git a/.github/actions/build_containers/action.yaml b/.github/actions/build_containers/action.yaml
--- a/.github/actions/build_containers/action.yaml
+++ b/.github/actions/build_containers/action.yaml
@@ -9,7 +9,6 @@ inputs:
   daemons:
     required: true
     type: string
-    default: "pmacctd nfacctd sfacctd uacctd pmbgpd pmbmpd pmtelemetryd"
   ci_num_workers:
     required: false
     type: string
@@ -28,6 +27,12 @@ runs:
         CI_DEPS_DONT_CHECK_CERTIFICATE: ${{ inputs.ci_deps_dont_check_cert }}
       shell: bash
       run: |
+        #Sanity, avoid regression #816
+        N_DAEMONS="$(echo $DAEMONS | wc --words)"
+        if [[ "${N_DAEMONS}" != "7" ]]; then
+            echo "ERROR: invalid number of DAEMONS: ${N_DAEMONS}"
+            exit 1
+        fi
         cd pmacct
         git config --global --add safe.directory $GITHUB_WORKSPACE
         git config --global --add safe.directory $GITHUB_WORKSPACE/src/external_libs/libcdada
